### ISSUE TITLE
Error while saving entries because of duplicate clientId

### ISSUE THREAD

**Issue by tnagorra** [the-deep/client#2279] opened 2021-12-10 03:57 UTC

**Comment by thenav56** [comment] 2022-01-17 05:47
@AdityaKhatri @tnagorra This is fixed on the client-side right?

**Comment by thenav56** [comment] 2022-01-17 08:53
If this occurs again. We will remove the clientId from database.

**Comment by tnagorra** [comment] 2022-01-21 04:15
This should be fixed from the server side.
Client is sending the data correctly.

**Comment by thenav56** [comment] 2022-04-13 03:53
@AdityaKhatri  @tnagorra Haven't seen this issue again. Should we close this issue? cc: @udaynwa

**Comment by thenav56** [comment] 2022-04-13 03:54
cc: @kumud02

**Comment by kumud02** [comment] 2022-04-13 06:08
The issue is not seen by the QA team and from the other users too. 
Task is closed for now.

**Closed as completed** 2022-04-13 06:09 UTC
Labels: bug, related-server
